/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.estudio.aplicacion.view;

import com.estudio.aplicacion.modelos.Ejemplar;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Telma
 */
public class MainView extends javax.swing.JFrame {
    
    //Lista de ejemplares
    private List<Ejemplar> ejemplares;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        ejemplares = new ArrayList<>(); //Inicializar lista
        
        //Ejemplares de prueba
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txBuscar = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txBuscar.setText("Buscar...");
        txBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBuscarActionPerformed
        // TODO add your handling code here:
        String textoBuscado = txBuscar.getText();
        Ejemplar ejemBuscado = buscarEjemplar(textoBuscado);
        if (ejemBuscado != null) {
            JOptionPane.showMessageDialog(this, "Ejemplar encontrado: " + ejemBuscado);
        } else {
            JOptionPane.showMessageDialog(this, "Ejemplar no encontrado.");
        }

        List<Ejemplar> listaBuscada = buscarEjemplares(textoBuscado);
        if (!listaBuscada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ejemplares encontrados: " + listaBuscada);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron ejemplares.");
        }

        
    }//GEN-LAST:event_txBuscarActionPerformed
    public Ejemplar buscarEjemplar(String nombre) {
        for (Ejemplar ejem : ejemplares) {
            if (ejem.getNombre().equals(nombre)) {
                return ejem;
            }
        }
        return null;  // Si no se encuentra el ejemplar
    }

    public List<Ejemplar> buscarEjemplares(String nombre) {
        List<Ejemplar> encontrados = new ArrayList<>();
        for (Ejemplar ejem : ejemplares) {
            if (ejem.getNombre().equals(nombre)) {  // Utiliza contains para búsqueda parcial
                encontrados.add(ejem);
            }
        }
        return encontrados;
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables
}
